export const COUNTER_INCREMENT = 'COUNTER_INCREMENT';
export const COUNTER_DECREMENT = 'COUNTER_DECREMENT';

export const DOCTORS_SUCCESS = 'DOCTORS_SUCCESS';
// export const DOCTORS_FAILURE = 'DOCTORS_FAILURE';



