export const COUNTER_INCREMENT = 'COUNTER_INCREMENT';
export const COUNTER_DECREMENT = 'COUNTER_DECREMENT';

export const DOCTORS_lOADING = 'DOCTORS_lOADING';
export const DOCTORS_ERROR = 'DOCTORS_ERROR';
export const DOCTORS_SUCCESS = 'DOCTORS_SUCCESS';
export const DOCTORS_ADD = 'DOCTORS_ADD';
export const DOCTORS_DELETE = 'DOCTORS_DELETE';
export const DOCTORS_UPDATE = 'DOCTORS_UPDATE';

export const MEDICINE_lOADING = 'MEDICINE_lOADING';
export const MEDICINE_ERROR = 'MEDICINE_ERROR';
export const MEDICINE_SUCCESS = 'MEDICINE_SUCCESS';
export const MEDICINE_ADD = 'MEDICINE_ADD';
export const MEDICINE_DELETE = 'MEDICINE_DELETE';
export const MEDICINE_UPDATE = 'MEDICINE_UPDATE';

export const Add_TO_CART = 'Add_TO_CART';
export const INCREMENT_QUANTITY = 'INC_QUNTITY';
export const DECREMENT_QUANTITY = 'DEC_QUNTITY';
export const REMOVE_ITEM = 'REMOVE_ITEM';